### ISSUE TITLE
CreateTopic does not allow to pass options (TopicDescription)

### ISSUE THREAD

**Issue by mswietlicki** [Mossharbor/AzureWorkArounds.ServiceBus#1]
Nice work overall!
Are you planning to implement more advanced features like creating topic with specific TopicDescription, add Name/Path to TopicDescription and other? 

Thanks,
Mateusz

**Comment by Mossharbor** [comment]
@mswietlicki Yep I was working on that this morning.  Create with a specific description gets a bit trickier to test thoroughly, so rollout is taking a bit longer.  But if you need a preview version I can work on getting that out.  I can also prioritize (for instance Topics over EventHubs if you have an immediate need).  Personally, I need Service Bus Topic configuration so that is up first.

**Comment by mswietlicki** [comment]
That's great news.
What we would like the most is the ability to create Subscriptions with filters and Topics with SupportOrdering property. Rest we can already do with your code :)

**Comment by Mossharbor** [comment]
@mswietlicki  Ok I updpated the nuget package to support updating queue's and topics.  No subscription update support yet.  I will work on that next.  Would you mind validating the SupportOrdering logic?  That seems to have some unusual logic behind it, I think what I have below is correct.  
```
        public bool SupportOrdering
        {
            get
            {
                if (supportOrderingField.HasValue)
                {
                    return supportOrderingField.GetValueOrDefault();
                }
                if (!this.EnablePartitioning && !this.EnableSubscriptionPartitioning)
                {
                    return true;
                }
                return false;
            }
            set
            {
                this.supportOrderingField = new bool?(value);
            }
        }

```

**Comment by Mossharbor** [comment]
Ok I added update and create of subscriptions in the *.5 release.  Filters are not implemented yet and should be next on my list.

**Comment by Mossharbor** [comment]
@mswietlicki Ok just updated the nuget package to the *.6 release.  This should allow SqlFilters and Correlation filters to be added.  I also added GetRules.  NOTE; correlation filters don't support user defined properties yet, but the other values should work.  That should be everything on your wishlist, please let me know if something is not working as you would expect.

**Comment by mswietlicki** [comment]
@Mossharbor Thanks!
I will test it today and let you know.
One more think. I notice we are also missing namespaceManager.GetSubscriptions(topic) that would help with cleanup.
Anyway great work :)
