### ISSUE TITLE
NamespaceManager.SubscriptionExists throws NullReferenceException

### ISSUE THREAD

**Issue by mswietlicki** [Mossharbor/AzureWorkArounds.ServiceBus#4]
Hi

If you call NamespaceManager.SubscriptionExists with long subscriptionName like "ServiceBusTest-f7b6c694-b264-40e1-bacb-0e30ca8b33e9" it throws "System.NullReferenceException : Object reference not set to an instance of an object."

This subscriptionName is probably to long and this is causing the problem but anyway NullReferenceException is not nice ;)

Regards,
Mateusz

**Comment by Mossharbor** [comment]
no problem thanks for letting me know.  I will see what I can do about throwing a better exception

**Comment by Mossharbor** [comment]
@mswietlicki  Should be fixed in the *.10 release.  Topic names/paths can be 260 characters and subscription/rule names at 50.  Anything else will throw a argument out of range exception.
