### ISSUE TITLE
CreatSubscription dos not set parameter RequiresSession

### ISSUE THREAD

**Issue by SergeBerwert** [Mossharbor/AzureWorkArounds.ServiceBus#7]
When I create a subscription it does not set the RequiresSession right. I need it to be false but its always true

**Comment by Mossharbor** [comment]
Hmm, investigating now.

**Comment by Mossharbor** [comment]
@SergeBerwert I am unsure how to reproduce what you are seeing.  The code below successfully creates a subscription with RequiresSession set to false.   Can you tell what you are doing different?
```
public void TestSubscriptionRequiresSession()
        {
            string name = "TestSubscriptionRequiresSession";
            string topicName = "TestSubscriptionRequiresSession";

            NamespaceManager ns = NamespaceManager.CreateFromConnectionString(serviceBusConnectionString);

            try
            {
                DeleteSafeTopic(ns, topicName);

                TopicDescription tdescription = ns.CreateTopic(topicName);
                SubscriptionDescription sdescription = new SubscriptionDescription(topicName, name);
                sdescription.RequiresSession = false;
                var outsd = ns.CreateSubscription(sdescription);
                Assert.IsTrue(null != tdescription);
                Assert.IsTrue(null != sdescription);
                Assert.IsFalse(outsd.RequiresSession);

                IEnumerable<SubscriptionDescription> suscriptions = ns.GetSubscriptions(topicName);
                Assert.IsTrue(suscriptions.First().Name.Equals(name));
            }
            finally
            {
                DeleteSafeTopic(ns, topicName);
            }

        }
```

**Comment by SergeBerwert** [comment]
Hi
in the meantime, I had time to explore the problem a little more. The code I did looked like that:

```
                var sd = new SubscriptionDescription(topic, clientName)
                {
                    RequiresSession = false,
                    LockDuration = TimeSpan.FromMinutes(1),
                    MaxDeliveryCount = 10,
                    EnableDeadLetteringOnMessageExpiration = true,
                    AutoDeleteOnIdle = TimeSpan.FromMinutes(5)
                };

                namespaceManager.CreateSubscription(sd);
```

But after calling that not all values were set properly. 

so I changed to:

```
                var sd = namespaceManager.CreateSubscription(topic, clientName);
                sd.RequiresSession = false;
                sd.LockDuration = TimeSpan.FromMinutes(1);
                sd.MaxDeliveryCount = 10;
                sd.AutoDeleteOnIdle = _isDevelopment ? TimeSpan.FromMinutes(5) : TimeSpan.FromHours(3);
                sd.DefaultMessageTimeToLive = TimeSpan.FromHours(96);

                namespaceManager.UpdateSubscription(sd);
```

as you can see I created the subscription and updated the value after. but however i could not set the value EnableDeadLetteringOnMessageExpiration = true. I got a bad request 400 back from the server.

Ich denke der Wert EnableDeadLetteringOnMessageExpiration war das Problem, warum die anderen Werte richtig gesetzt wurden.

Thanks for the work any way, great job.

**Comment by Mossharbor** [comment]
When you say "_But after calling that not all values were set properly."_ What values were not set properly?

**Comment by Mossharbor** [comment]
@SergeBerwert  ok I figured out what is happening a fix has been submitted and should be in the *.16 build (from nuget).  It seems like setting EnableDeadLetteringOnMessageExpiration was actually setting requires session.

**Comment by SergeBerwert** [comment]
Hi
Thanks a lot all values are now set right. I appreciate the fast help. I consider the issue as closed.
